### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by jwb009** [benjamminf/craft-embedded-assets#10]
I'm having trouble getting the plugin to save videos with 0.2.0.... I keep getting an Uncaught TypeError. I can search for videos fine, but trying to save brings up this error:

`Uncaught TypeError: Cannot read property 'id' of undefined  EmbeddedAssets.js:49`

This is on a localhost (WAMP) server, Craft 2.5.2761

Thanks!

**Comment by benjamminf** [comment]
Thanks for reporting! Seems like 0.2.0 is having quite a few issues. What browser are you using?

**Comment by jwb009** [comment]
Hi, using Chrome 48.0.2564.103 on Win 7. Haven’t tested Firefox or IE yet.
Thanks for replying though, very cool plugin.

**Comment by benjamminf** [comment]
Looking into this, it seems like adding the embedded asset is failing at some point, and that failure is not being picked up. I've implemented better error checking and reporting so hopefully this will solve your issue.
