### ISSUE TITLE
Flickr album URLs don't work

### ISSUE THREAD

**Issue by icopp** [benjamminf/craft-embedded-assets#12]
For a simple example using a random public album:
- Plug in https://www.flickr.com/photos/roddieu2/albums/72157651895021518
- Get the message "Could not find any embeddable media from this URL."

However, look at https://www.flickr.com/services/oembed/?url=https://www.flickr.com/photos/roddieu2/albums/72157651895021518 and you see a JSON result with link, thumbnail, title, and html content data.

**Comment by benjamminf** [comment]
It seems the Flickr album page doesn't list the oEmbed info on the page. The Essence library scans the page for a `<link type="...+oembed">` tag but the album page doesn't have one.

I want to refrain from putting in special cases as websites change and the special cases will constantly need to be updated. It's also not the plugin's responsibility.

However, I have [embed.ly](http://embed.ly/) integration on the [to-do list](https://github.com/benjamminf/craft-embedded-assets/issues/3), which will capture all these edge cases where some sites don't provide their embed data correctly (just tested it with the Flickr album and works perfectly). I don't have an ETA for this feature but I'll be looking into it this weekend.

**Comment by i-c** [comment]
Oh, nice to hear.

**Comment by benjamminf** [comment]
Now somewhat supported in the Craft 3 version.

Flickr is no longer included in the whitelist by default, and must be manually added. Unfortunately there's no way to pull entire galleries from Flickr, only single images.
