### ISSUE TITLE
Embedded Assets doesn't account for json files in subfolders

### ISSUE THREAD

**Issue by icopp** [benjamminf/craft-embedded-assets#14]
If you have a Local Files assets type, use Embedded Assets and in Assets put the item into a subfolder, Embedded Assets still tries to access it at the root level (e.g. `/assets/dogs/yaddayadda.json` versus `/assets/yaddayadda.json`).

If there are any substantial number of Embedded Assets files in folders, this can slow the control panel down by 30+ seconds because it tries to load each at the root level and gets 404s instead of json files.

**Comment by benjamminf** [comment]
Thanks for reporting! I can't seem to reproduce this issue. I have attempted moving existing embedded assets into folders, as well as creating them inside the folder, but I'm not experiencing any 404's.

What version of Craft and Embedded Assets are you running?

**Comment by i-c** [comment]
This is using Craft 2.6.2780 and EA 0.3.1, but the problem cropped up immediately after upgrading from EA 0.2.1.

**Comment by benjamminf** [comment]
I've merged #28 which apparently addresses this issue. I've never been able to reproduce this so I can't say for certain that this is fixed, but I'll be closing this issue. If you still have problems I'll reopen it.
