### ISSUE TITLE
CP requests hang if there's an issue getting any thumbnail URLs

### ISSUE THREAD

**Issue by mdcpepper** [benjamminf/craft-embedded-assets#15]
Hello,

I have this plugin installed and it has been working great on a site, but any CP request was taking well over a minute to load, if at all. After a bit of investigation I traced it to the `EmbeddedAssetsModel::populateFromAsset()` method, which I think is run for every embedded asset, on every non-Ajax CP request. 

This attempts to read the .json file to get the thumbnail URL, but the `file_get_contents()` call has its errors suppressed with '@'. After removing that I found that a warning was/should have been triggered for one of the assets on our S3-backed asset source:

> file_get_contents(https://ca1-tls.edcdn.com/embed_065cfea0-46ef-4683-98c2-4ab42f68973e.json?mtime=20160406103454): failed to open stream: HTTP request failed! HTTP/1.1 403 Forbidden

Which is obviously not ideal in the first place, but because of the error suppression, PHP seemed to just stall, at least for a full minute, sometimes it doesn't load at all, and it's happening on every CP request, even for the login page.

Could there also be an issue with this if the client adds 1000 embedded assets, would every CP request make 1000 calls to S3 for those files?

Thanks for the plugin, and any help you can offer!

**Comment by benjamminf** [comment]
Hey, sorry for the late response! Spare time has been devoted to one of my other plugins (Neo), but with that being released this coming week I'll be jumping back into EA.

First off, thanks for the very detailed report. Seems odd that S3 would forbid access to the file, in which case there's not a lot the plugin can do about that. Also would have not expected the server to stall on a 403 response for so long.

But it's shown a problem with how I'm getting thumbnails. Currently I'm just greedily loading every embedded asset on every page on the off chance an asset index is or can be visible. I should absolutely implement caching for this so it doesn't have to request and parse every embedded asset JSON file every page request.

I should have this fixed some time next week.

Thanks, Ben.

**Comment by benjamminf** [comment]
Fixed in the upcoming release
