### ISSUE TITLE
500 Error, asset URL doesn't resolve

### ISSUE THREAD

**Issue by darylknight** [benjamminf/craft-embedded-assets#16]
Embedded Assets is working fine on my local dev machine. When I try to add a YouTube link on my staging domain though, I paste a URL into the bar:

![screen shot 2016-04-28 at 10 43 57](https://cloud.githubusercontent.com/assets/1250017/14881911/115e74f8-0d2e-11e6-93ed-62d0242bd3f5.png)

I just see a wheel turning constantly as if it's continually processing. In the console, I'm seeing the following error:

![error](https://cloud.githubusercontent.com/assets/1250017/14881899/ffe948d8-0d2d-11e6-96d0-f9bca11ed557.jpg)

Any ideas?

**Comment by benjamminf** [comment]
Hey @darylknight thanks for the report! From what I can tell, the `EmbeddedAssetsService::parseUrl` method is causing a server error for some reason. Since I'm wrapping a try/catch statement around most of that method, the only thing that could be causing a 500 error is the Essence PHP library. What version of PHP are you running? Essence requires minimum 5.5

**Comment by benjamminf** [comment]
If you add the following code inside the `EmbeddedAssetsController` class, this will let you inspect the server error:

	protected $allowAnonymous = ['testUrl'];

	public function actionTestUrl()
	{
		$url = craft()->request->getQuery('url');
		$media = craft()->embeddedAssets->parseUrl($url);

		echo '<pre><code>';
		var_dump($media);
		echo '</code></pre>';
		
		exit;
	}

Then just visit `yoursite.com/actions/embeddedAssets/testUrl?url=http://youtube.com...` and see what happens

**Comment by darylknight** [comment]
Hi Ben - thanks for getting back to me so fast. Your first instinct was right, I'd forgotten to crank up the PHP version on my staging server and it was running 5.4. Changed it to PHP 7 and everything's fine now. Thanks for a great plugin!

**Comment by benjamminf** [comment]
Ah awesome, it's usually never that simple! I'll add a check in the plugin for the PHP version so this doesn't catch anybody out again. Cheers! Ben.
