### ISSUE TITLE
Use of mime_content_type breaks on some systems

### ISSUE THREAD

**Issue by i-c** [benjamminf/craft-embedded-assets#17]
In `services/EmbeddedAssetsService.php`, `mime_content_type()` is used.

However, this function comes from [a deprecated library](http://www.php.net/manual/en/fileinfo.installation.php) and doesn't exist at all in some vendor builds of PHP 5.3+. This makes any attempt to upload an embedded asset fail silently on these systems, because `mime_content_type()` is undefined.

**Comment by benjamminf** [comment]
Hey thanks for the report. The PHP docs don't directly say anything about the deprecation of `mime_content_type` on that functions page so I never knew. Thanks for the heads up, it's fixed now!
