### ISSUE TITLE
Support for YouTube embed ID as a parameter

### ISSUE THREAD

**Issue by robzor** [benjamminf/craft-embedded-assets#18]
Hi there,

Love the add-on, but having an issue with a modal plugin where it wants youtube URL in this format:

`https://www.youtube.com/embed/<video ID>`

Is it possible for you to add another parameter to the output options? I was trying to work it out myself but got nowhere :(

Thanks,

Rob

**Comment by benjamminf** [comment]
Hey Rob, sorry for the late reply!

EA is built to accept any link that contains oEmbed data. This means the plugin won't contain any special cases for things like extracting YouTube ID's.

That said, this is something you could do quite easily in your Twig template:

```twig
{% set embed = craft.embeddedAssets.fromAsset(asset) %}
{% if embed.providerName|lower == 'youtube' %}
    {% set videoId = embed.url|replace('/.+watch\?v=(.+)/', '$1') %}
    {% set modalUrl = 'https://www.youtube.com/embed/' ~ $videoId %}
{% endif %}
```

This will use a regular expression to find the ID from the YouTube URL.

**Comment by robzor** [comment]
Hi @benjamminf , no worries! I did do something along the same lines as you suggested, and I understand you wanting to adhere to the oEmbed specs. 

Thanks for getting back to me though :)

**Comment by pioneerdesign** [comment]
How could we use this solution for multiple videos in the same field?
```
{% set asset = block.videoAsset.all() %} 
{% for asset in block.videoAsset.all() %}  	
 	{% set embeddedAsset = craft.embeddedAssets.get(asset) %}
 	  {% if embeddedAsset.providerName|lower == 'youtube' %}    
 		   {% set videoId = embed.url|replace('/.+watch\\?v=(.+)/', '$1') %}
 	  {% endif %}
         ... 
        https://youtu.be/{{ videoId }}
{% endfor %}
```
