### ISSUE TITLE
Please add FlowPlayer.org to whitelist

### ISSUE THREAD

**Issue by fixxer37** [benjamminf/craft-embedded-assets#20]
Hi,
I really like the plugin, could you please add support for flowplayer? It's most likely just the whitelist that needs updating - I'm fairly certain flowplayer should embed due to its wide range of formats and embedding options. It provides a lot of control over how the video displays etc.

many thanks

**Comment by benjamminf** [comment]
Hey @fixxer37 cheers! Updating the whitelist is simple enough. Do you have an example link that uses flowplayer? From what I can tell, flowplayer is just a video player with optional hosting, so it doesn't actually handle any of the information about how it's embedded. That would be up to the website that's using the player. So all I can really do is add it to the whitelist for websites that use it's hosting service.

**Comment by fixxer37** [comment]
Hi, thank you for your reply. You're correct that flowplayer is the video player, but I should have clarified - flowplayer.org (flowplayer drive) hosts the media (as an paid service) where it re-encodes as both html5 webm and mp4 in differing quality versions and compatibility plus has cdn etc.
Here is an example share url: https://flowplayer.org/share/179328b9;154439
it also provides multiple embed options and its own standalone page.
Here's just one sample of html5 embedding:
<video loop>
  <source type="application/x-mpegurl" src="//cdn.flowplayer.org/258711/154439.m3u8">
  <source type="video/webm" src="//cdn.flowplayer.org/258711/154439.webm">
  <source type="video/mp4" src="//cdn.flowplayer.org/258711/154439.mp4">
</video>

from what I could see it doesn't output an oembed tag mentioned in the documentation. It does however provide all the thumbnail and embed content required by most social media sites etc. 
Thanks in advance

**Comment by benjamminf** [comment]
Ah okay, thanks for the link. In recent versions of EA, I added a fallback to Open Graph metadata. Actually surprised it's not working right now. It's probably not looking at enough attributes or something minor like that. I'll get on it soon.

**Comment by benjamminf** [comment]
Now supported in Craft 3 version.
