### ISSUE TITLE
PHP Error

### ISSUE THREAD

**Issue by darylknight** [benjamminf/craft-embedded-assets#21]
Hiya,

I'm trying to use Embedded Assets on an existing site - it's hosted on Windows (don't blame me). I've created a new Assets folder and I can upload images into it, but when I try to embed a video, I get a Unknown Error Occured red box appear at the top of the screen. The server PHP version is 5.5.11.

`phperrors.log` has this to say about it:

    [01-Jun-2016 09:35:08 UTC] PHP Fatal error:  Call to undefined function Craft\finfo_open() in C:\Client_Sites\mysite.co.uk\craft\plugins\embeddedassets\services\EmbeddedAssetsService.php on line 250

I've got a yellow warning triangle next to `fileinfo extension` on Utils. Could that be it?

Thanks,
Daryl

**Comment by benjamminf** [comment]
Hey Daryl, thanks for the report!

The `fileinfo` extension needs to be enabled. If there's a warning sign next to it, it might be an old or broken version of the extension.

Funnily enough, I only introduced the need for the `fileinfo` extension to fix a bug (#7) about `mime_content_type()` not working in some later versions of PHP (5.3+). It wouldn't be hard to add back in `mime_content_type()` as a fallback.

**Comment by darylknight** [comment]
Thanks Ben - it's not a site I host so I've put in a request to their company to enable it. Any idea off the top of your head if there's a specific version of it that needs to be enabled?

**Comment by benjamminf** [comment]
Unfortunately, I can't say what it could be. I figured with it fresh in my mind, and being an easy fix, I've gone ahead and written a fallback if the `fileinfo` extension isn't usable. It should be available on the master branch. Let me know if it does or doesn't work :+1:

**Comment by darylknight** [comment]
Thanks Ben. That seems to let me upload assets again, but I can't get them to display in my template. Your example code has worked fine on other sites, so I'm wondering if there's an issue with the uploaded files or detection.

    {% for video in block.asset %}
        <p>{{ video.title }}</p>
        {% set embed = craft.embeddedAssets.fromAsset(video) %}
        <p>Length: {{ embed|length }}</p>
        {% if embed %}
            {{ embed.safeHtml|raw }}
        {% endif %}
    {% endfor %}

The code above outputs the video's title, so Craft knows the asset is there and exists, but it also outputs `Length: 0`, so it looks like EA isn't recognising it as an asset. Am I correct in thinking that's what's going on? Where am I going wrong?

**Comment by benjamminf** [comment]
Hm, that's interesting. It seems like the file isn't being read. I'm using two methods of reading the contents of the JSON file, through `cURL`, and `file_get_contents` as a fallback. Pretty low chance of both of those not being available, but it might be the case. Do you know if the `curl` extension is enabled?

**Comment by darylknight** [comment]
cURL support has a green tick next to it in `/utils`

**Comment by benjamminf** [comment]
Also, just to be safe, can you check the contents of the JSON file that gets generated? Want to make sure it's being uploaded okay.

**Comment by darylknight** [comment]
Contents of test json file:

    {"type":"video","url":"http:\/\/www.youtube.com\/watch?v=LBc7X8gMPwg","requestUrl":"https:\/\/www.youtube.com\/watch?v=LBc7X8gMPwg","title":"Dreamstate Logic - Galaxy's Child","description":"In order to more fully understand this reality, we must take into account other dimensions of a broader reality, the introduction of higher dimensions of con...","authorName":"SpaceAmbient","authorUrl":"https:\/\/www.youtube.com\/user\/SpaceAmbient","providerName":"YouTube","providerUrl":"https:\/\/www.youtube.com\/","cacheAge":"","thumbnailUrl":"https:\/\/i.ytimg.com\/vi\/LBc7X8gMPwg\/hqdefault.jpg","thumbnailWidth":"480","thumbnailHeight":"360","html":"<iframe width=\"1280\" height=\"720\" src=\"https:\/\/www.youtube.com\/embed\/LBc7X8gMPwg?feature=oembed\" frameborder=\"0\" allowfullscreen><\/iframe>","safeHtml":"<iframe width=\"1280\" height=\"720\" src=\"https:\/\/www.youtube.com\/embed\/LBc7X8gMPwg?feature=oembed\" frameborder=\"0\"><\/iframe>","width":"1280","height":"720","__embeddedasset__":true}

**Comment by benjamminf** [comment]
Everything seems like it should be fine. Clearly the problem is in reading the file, but I'm not sure why that would be failing. If you locate the `_readExternalFile` method in EmbeddedAssetsService, this is where the file is being read. Try adding in some `var_dump(); exit;`'s on some of the variables, to see where it's breaking. `curl_error()` might be throwing an error that I'm just ignoring.

Sorry I can't be much more of a help!

**Comment by darylknight** [comment]
Ok no worries Ben - I'll do some digging and let you know if I find anything. Otherwise I'll assume it's down to their Windows hosting. Thank you for your time :)
