### ISSUE TITLE
How to remove frameborder attribute from iframe?

### ISSUE THREAD

**Issue by OneX** [benjamminf/craft-embedded-assets#216]
#### Description

When Craft GraphQL return the iframeCode it includes the frameborder attribute. This is provoking the following w3 validation error:

Error: The frameborder attribute on the iframe element is obsolete. Use CSS instead.

Is there a way to remove that attribute from iframe code?

#### Steps to reproduce
1. Check iframeCode in GraphQL query

#### Other information
- Embedded Assets version: 2.10.7
- Craft CMS version: 3.7.43

**Comment by ttempleton** [comment]
There's currently no in-built way to remove iframe attributes, but that's something we can look at for a future release.

**Comment by OneX** [comment]
@ttempleton great. Thanks for informing us.
