### ISSUE TITLE
Parameters Missing

### ISSUE THREAD

**Issue by superflausch** [benjamminf/craft-embedded-assets#22]
I added a parameter (showinfo=0) to the plugins settings page with the goal to hide youtubs info bar. Unfortunately this doesn't work and the bar is still there. When I check the request in the browser console the parameter is missing.

Any ideas what I'm missing?

Cheers, Pascal.

**Comment by benjamminf** [comment]
The parameters should be sending via post, so you won't see them in the URL. Annoyingly YouTube's oEmbed doesn't support anything other than `maxwidth` and `maxheight` parameters, so there's nothing the plugin can really do about that. To get around this, I don't actually use the embed HTML provided by YouTube, and instead build my own. [Using this method to get YouTube ID's](https://github.com/benjamminf/craft-embedded-assets#how-can-i-get-youtubevimeo-ids), I rebuild the `<iframe>` element myself. Here's a macro you could use if you're interested:

```twig
{% macro embedYouTube(id, settings = {}) %}
    {% set params = [] %}
    {% for name, value in settings %}
        {% set params = params|merge([name|e('url') ~ '=' ~ value|e('url')])
    {% endfor %}
    {% set url = '//youtube.com/embed/' ~ id ~ '?' ~ params|join('&') %}
    <iframe src="{{ url }}" frameborder="0" allowfullscreen></iframe>
{% endmacro %}
```

You can use like this:

```twig
{{ embedYouTube('VIDEOID', {showinfo: 0, autoplay: 1}) }}
```

**Comment by laurabennett** [comment]
Looks like there should be a playerVars object available in the API for the additional params.
https://developers.google.com/youtube/iframe_api_reference#Loading_a_Video_Player
https://developers.google.com/youtube/player_parameters.html?playerVersion=HTML5#Parameters
