### ISSUE TITLE
Error for (Youtube) videos with special characters in title 

### ISSUE THREAD

**Issue by dommmel** [benjamminf/craft-embedded-assets#23]
I am experiencing an strange behaviour where some youtube videos would keep showing up as JSON file type instead of "Embedded video".

**Comment by dommmel** [comment]
Sorry fat fingers. So the pattern seems to be: 
It happens If a video has a special character (in my case ® ) in the title.

e.g. https://www.youtube.com//watch?v=bzpR14NHq2s

**Comment by benjamminf** [comment]
Hm this is strange. I actually run a filename cleansing function that's in Craft to remove these extended characters, but it seems to be failing on that title. I've just rolled my own that works, will release a fix now.

**Comment by dommmel** [comment]
Thanks for the fast support!
