### ISSUE TITLE
500 (Internal Server Error) on save

### ISSUE THREAD

**Issue by pixeljitsu** [benjamminf/craft-embedded-assets#25]
When I try to save a link I get `/actions/embeddedAssets/saveEmbeddedAsset 500 (Internal Server Error)`

The modal shows the preview just fine but I can not save at all. 

PHP 7, Craft CMS 2.6.2903, MAMP, HTTPS

**Comment by benjamminf** [comment]
Is this happening for every link or just one specifically? If it's just one, can you provide the link that's not working?

**Comment by pixeljitsu** [comment]
Every link.  I tried YouTube and Viimeo links..  Both looked fine until submit which 500s

**Comment by klepl** [comment]
I just installed the plugin and having the same issue - the preview is shown but can't save. A 500 error is shown in the console and apache log.

/index.php/admin/actions/embeddedAssets/saveEmbeddedAsset 500 (Internal Server Error)

How to find out details of the error?

**Comment by klepl** [comment]
Still not able to figure out what's going on here. The error is happening only locally on my Mac environment. Seems to be working fine remotely (ubuntu). I'm unable to find any details on the 500 error. Any ideas?

**Comment by benjamminf** [comment]
Key @klepl, I've released 0.3.4 which adds logging into the plugin. Can you install the latest version, try adding an asset, then upload the `craft/storage/runtime/logs/embeddedassets.log` file here (or send it to @benf on Craft's Slack channel)? Thanks.

**Comment by klepl** [comment]
Awesome, thanks Ben, I will be able to give this a try next week. I will let you know how it goes...

**Comment by klepl** [comment]
Hi Ben, Here are excerpts from two logs. The first excerpt is from my local mac environment where the embed silently failed. The second is from the remote ubuntu environment where the embed was successful.

FAILED EMBED (Local Environment)

******************************************************************************************************
2016/09/22 01:50:43 [info] [plugin] Requesting URL "https://www.youtube.com/watch?v=xxx"
in /Volumes/site/craft/app/etc/plugins/BasePlugin.php (65)
in /Volumes/site/craft/plugins/embeddedassets/services/EmbeddedAssetsService.php (61)
in /Volumes/site/craft/plugins/embeddedassets/controllers/EmbeddedAssetsController.php (12)
2016/09/22 01:50:44 [info] [plugin] Embed data found
in /Volumes/site/craft/app/etc/plugins/BasePlugin.php (65)
in /Volumes/site/craft/plugins/embeddedassets/services/EmbeddedAssetsService.php (67)
in /Volumes/site/craft/plugins/embeddedassets/controllers/EmbeddedAssetsController.php (12)
2016/09/22 01:50:44 [info] [plugin] Some data missing - looking for related Open Graph metadata
in /Volumes/site/craft/app/etc/plugins/BasePlugin.php (65)
in /Volumes/site/craft/plugins/embeddedassets/services/EmbeddedAssetsService.php (81)
in /Volumes/site/craft/plugins/embeddedassets/controllers/EmbeddedAssetsController.php (12)
2016/09/22 01:50:44 [info] [plugin] Reading file with `curl`
in /Volumes/site/craft/app/etc/plugins/BasePlugin.php (65)
in /Volumes/site/craft/plugins/embeddedassets/services/EmbeddedAssetsService.php (303)
in /Volumes/site/craft/plugins/embeddedassets/services/EmbeddedAssetsService.php (85)

******************************************************************************************************
2016/09/22 01:50:46 [info] [plugin] Setting embedded asset file mime type with `finfo`
in /Volumes/site/craft/app/etc/plugins/BasePlugin.php (65)
in /Volumes/site/craft/plugins/embeddedassets/services/EmbeddedAssetsService.php (271)
in /Volumes/site/craft/plugins/embeddedassets/services/EmbeddedAssetsService.php (237)

******************************************************************************************************


SUCCESSFUL EMBED (Remote Environment)

******************************************************************************************************
2016/09/22 01:54:14 [info] [plugin] Requesting URL "https://www.youtube.com/watch?v=xxx"
in /var/www/site/craft/app/etc/plugins/BasePlugin.php (65)
in /var/www/site/craft/plugins/embeddedassets/services/EmbeddedAssetsService.php (61)
in /var/www/site/craft/plugins/embeddedassets/controllers/EmbeddedAssetsController.php (12)
2016/09/22 01:54:14 [info] [plugin] Embed data found
in /var/www/site/craft/app/etc/plugins/BasePlugin.php (65)
in /var/www/site/craft/plugins/embeddedassets/services/EmbeddedAssetsService.php (67)
in /var/www/site/craft/plugins/embeddedassets/controllers/EmbeddedAssetsController.php (12)
2016/09/22 01:54:14 [info] [plugin] Some data missing - looking for related Open Graph metadata
in /var/www/site/craft/app/etc/plugins/BasePlugin.php (65)
in /var/www/site/craft/plugins/embeddedassets/services/EmbeddedAssetsService.php (81)
in /var/www/site/craft/plugins/embeddedassets/controllers/EmbeddedAssetsController.php (12)
2016/09/22 01:54:14 [info] [plugin] Reading file with `curl`
in /var/www/site/craft/app/etc/plugins/BasePlugin.php (65)
in /var/www/site/craft/plugins/embeddedassets/services/EmbeddedAssetsService.php (303)
in /var/www/site/craft/plugins/embeddedassets/services/EmbeddedAssetsService.php (85)

******************************************************************************************************
2016/09/22 01:54:16 [info] [plugin] Setting embedded asset file mime type with `finfo`
in /var/www/site/craft/app/etc/plugins/BasePlugin.php (65)
in /var/www/site/craft/plugins/embeddedassets/services/EmbeddedAssetsService.php (271)
in /var/www/site/craft/plugins/embeddedassets/services/EmbeddedAssetsService.php (237)

******************************************************************************************************
2016/09/22 01:54:17 [info] [plugin] Reading file with `curl`
in /var/www/site/craft/app/etc/plugins/BasePlugin.php (65)
in /var/www/site/craft/plugins/embeddedassets/services/EmbeddedAssetsService.php (303)
in /var/www/site/craft/plugins/embeddedassets/services/EmbeddedAssetsService.php (209)
2016/09/22 01:54:17 [info] [plugin] Reading file with `curl`
in /var/www/site/craft/app/etc/plugins/BasePlugin.php (65)
in /var/www/site/craft/plugins/embeddedassets/services/EmbeddedAssetsService.php (303)
in /var/www/site/craft/plugins/embeddedassets/services/EmbeddedAssetsService.php (209)
2016/09/22 01:54:17 [info] [plugin] Reading file with `curl`
in /var/www/site/craft/app/etc/plugins/BasePlugin.php (65)
in /var/www/site/craft/plugins/embeddedassets/services/EmbeddedAssetsService.php (303)
in /var/www/site/craft/plugins/embeddedassets/services/EmbeddedAssetsService.php (209)
2016/09/22 01:54:17 [info] [plugin] Reading file with `curl`
in /var/www/site/craft/app/etc/plugins/BasePlugin.php (65)
in /var/www/site/craft/plugins/embeddedassets/services/EmbeddedAssetsService.php (303)
in /var/www/site/craft/plugins/embeddedassets/services/EmbeddedAssetsService.php (209)
2016/09/22 01:54:17 [info] [plugin] Reading file with `curl`
in /var/www/site/craft/app/etc/plugins/BasePlugin.php (65)
in /var/www/site/craft/plugins/embeddedassets/services/EmbeddedAssetsService.php (303)
in /var/www/site/craft/plugins/embeddedassets/services/EmbeddedAssetsService.php (209)
2016/09/22 01:54:17 [info] [plugin] Reading file with `curl`
in /var/www/site/craft/app/etc/plugins/BasePlugin.php (65)
in /var/www/site/craft/plugins/embeddedassets/services/EmbeddedAssetsService.php (303)
in /var/www/site/craft/plugins/embeddedassets/services/EmbeddedAssetsService.php (209)
2016/09/22 01:54:17 [info] [plugin] Reading file with `curl`
in /var/www/site/craft/app/etc/plugins/BasePlugin.php (65)
in /var/www/site/craft/plugins/embeddedassets/services/EmbeddedAssetsService.php (303)
in /var/www/site/craft/plugins/embeddedassets/services/EmbeddedAssetsService.php (209)
2016/09/22 01:54:17 [info] [plugin] Reading file with `curl`
in /var/www/site/craft/app/etc/plugins/BasePlugin.php (65)
in /var/www/site/craft/plugins/embeddedassets/services/EmbeddedAssetsService.php (303)
in /var/www/site/craft/plugins/embeddedassets/services/EmbeddedAssetsService.php (209)
2016/09/22 01:54:17 [info] [plugin] Reading file with `curl`
in /var/www/site/craft/app/etc/plugins/BasePlugin.php (65)
in /var/www/site/craft/plugins/embeddedassets/services/EmbeddedAssetsService.php (303)
in /var/www/site/craft/plugins/embeddedassets/services/EmbeddedAssetsService.php (209)
2016/09/22 01:54:17 [info] [plugin] Reading file with `curl`
in /var/www/site/craft/app/etc/plugins/BasePlugin.php (65)
in /var/www/site/craft/plugins/embeddedassets/services/EmbeddedAssetsService.php (303)
in /var/www/site/craft/plugins/embeddedassets/services/EmbeddedAssetsService.php (209)
2016/09/22 01:54:17 [info] [plugin] Reading file with `curl`
in /var/www/site/craft/app/etc/plugins/BasePlugin.php (65)
in /var/www/site/craft/plugins/embeddedassets/services/EmbeddedAssetsService.php (303)
in /var/www/site/craft/plugins/embeddedassets/services/EmbeddedAssetsService.php (209)
2016/09/22 01:54:17 [info] [plugin] Reading file with `curl`
in /var/www/site/craft/app/etc/plugins/BasePlugin.php (65)
in /var/www/site/craft/plugins/embeddedassets/services/EmbeddedAssetsService.php (303)
in /var/www/site/craft/plugins/embeddedassets/services/EmbeddedAssetsService.php (209)
2016/09/22 01:54:17 [info] [plugin] Reading file with `curl`
in /var/www/site/craft/app/etc/plugins/BasePlugin.php (65)
in /var/www/site/craft/plugins/embeddedassets/services/EmbeddedAssetsService.php (303)
in /var/www/site/craft/plugins/embeddedassets/services/EmbeddedAssetsService.php (209)
2016/09/22 01:54:17 [info] [plugin] Reading file with `curl`
in /var/www/site/craft/app/etc/plugins/BasePlugin.php (65)
in /var/www/site/craft/plugins/embeddedassets/services/EmbeddedAssetsService.php (303)
in /var/www/site/craft/plugins/embeddedassets/services/EmbeddedAssetsService.php (209)
2016/09/22 01:54:17 [info] [plugin] Reading file with `curl`
in /var/www/site/craft/app/etc/plugins/BasePlugin.php (65)
in /var/www/site/craft/plugins/embeddedassets/services/EmbeddedAssetsService.php (303)
in /var/www/site/craft/plugins/embeddedassets/services/EmbeddedAssetsService.php (209)
2016/09/22 01:54:17 [info] [plugin] Reading file with `curl`
in /var/www/site/craft/app/etc/plugins/BasePlugin.php (65)
in /var/www/site/craft/plugins/embeddedassets/services/EmbeddedAssetsService.php (303)
in /var/www/site/craft/plugins/embeddedassets/services/EmbeddedAssetsService.php (209)

******************************************************************************************************

**Comment by leevigraham** [comment]
Same issue with the version 0.3.4. I'll try and debug.

**Comment by benjamminf** [comment]
Nice debugging there @leevigraham! [Seems like this line](https://github.com/benjamminf/craft-embedded-assets/blob/master/embeddedassets/services/EmbeddedAssetsService.php#L263) is the cause for that. I'll have to find a way to detect the proper `tmp` folder location.

**Comment by leevigraham** [comment]
@benjamminf one debug step ahead of you.

`$tempName = tempnam(sys_get_temp_dir(), 'php_files');` will get you the system temp directory. 

However that still doesn't fix the issue. The `rename()` method is failing.

**Comment by benjamminf** [comment]
Is it perhaps the `rename` method fails on files inside the system temp directory? Maybe it's better to use Craft's `storage/runtime` directory, if that'll work?

**Comment by leevigraham** [comment]
It is strange. File perms for both the .json and a craft asset are the same. I'll try the `storage/runtime` dir now.

**Comment by benjamminf** [comment]
Try this `$tempName = tempnam(realpath(__DIR__ . '/../../') . '/storage/runtime/assets/', 'embeddedasset_');` it seems to be working for me

**Comment by leevigraham** [comment]
Created a WIP PR https://github.com/benjamminf/craft-embedded-assets/pull/31
