### ISSUE TITLE
Youtube Maxres Thumbnail

### ISSUE THREAD

**Issue by DTesch-Level-R** [benjamminf/craft-embedded-assets#259]
### Bug Description

For YouTube Assets the fetched image is always "hqdefault"
How can I force to fetch the maxres-Image?

### Steps to reproduce

1. Fetch Youtube-Video
2. image-Tag contains always the "hqdefault" Thumbnail 

### Embedded Assets version

4.1.0

### Craft CMS version

4.8.10

**Comment by ttempleton** [comment]
[Not all YouTube videos have a maxresdefault image](https://stackoverflow.com/questions/11334710/youtube-thumbnail-link-doesnt-work-in-all-cases), so I'm comfortable with hqdefault being what we attach to embedded assets.

If you have an embedded asset for a YouTube video that does have a maxresdefault image, you could either manually make that change in the JSON file, or you could do something like the following in your templates:

```twig
{% set maxResImage = embeddedAsset.image|replace({
  hqdefault: 'maxresdefault',
}) %}
```
