### ISSUE TITLE
Error uploading the file: This file type is not allowed

### ISSUE THREAD

**Issue by Takaya213** [benjamminf/craft-embedded-assets#26]
I have created an asset field, but when I try to add an embed link via the button, it gives me the error **Error uploading the file: This file type is not allowed**. Have no idea why as I have not set any restrictions on the field at all.

**Comment by benjamminf** [comment]
You need to modify your `config.php` file to include the `.json` file extension. [See the installation instructions.](https://github.com/benjamminf/craft-embedded-assets#installation)

**Comment by Takaya213** [comment]
Oh, sorry my bad, thanks for pointing out my lack of reading.

**Comment by benjamminf** [comment]
Haha all good :+1:
