### ISSUE TITLE
Getting ahead of security changes for Vimeo

### ISSUE THREAD

**Issue by RandomJo** [benjamminf/craft-embedded-assets#260]
### What question would you like to ask?

I am wondering if y'all have made any changes to support the new embed code needed to work with security changes that will be enforced on January 25, 2025?

https://help.vimeo.com/hc/en-us/articles/13741122177169-FAQ-Enhancing-the-security-of-Vimeo-embeds

**Comment by ttempleton** [comment]
Any changes required at any point for Vimeo compatibility would likely be implemented in the Embed package that this plugin uses, so all we would need to do is to update our Embed version requirement.
