### ISSUE TITLE
Vimeo URLs showing "Vimeo / CAPTCHA Challenge"

### ISSUE THREAD

**Issue by russback** [benjamminf/craft-embedded-assets#264]
### Bug Description

Using the Embed button at /admin/assets, we are seeing that the video is not being retrieved on preview and instead, this message displays. Using https://vimeo.com/70591644 as an example:

<img width="565" alt="Screenshot 2024-07-02 at 12 28 48" src="https://github.com/spicywebau/craft-embedded-assets/assets/2589006/92cfee72-834f-477f-a048-1172589081f5">

We are seeing this on the latest Craft and Embedded Assets version and also legacy sites, so wonder if this a change at Vimeo's end. YouTube URLs are behaving as expected in the same workflow.

### Steps to reproduce

1. Click the Embed button at /admin/assets
2. Enter the URL https://vimeo.com/70591644

### Embedded Assets version

5.1.0

### Craft CMS version

5.2.4.1

**Comment by ttempleton** [comment]
This is working as expected for me:

![Screenshot 2024-07-03 at 00-06-45 Assets - Craft 5 Plugin Dev](https://github.com/spicywebau/craft-embedded-assets/assets/19421878/983794ae-f291-445d-b88f-cda2d552faef)

That said, Embedded Assets is using the [Embed](https://github.com/oscarotero/Embed) package to get Vimeo embed data - so I will recommend that you set up a basic test using Embed directly, to rule out it being a plugin issue. Please let me know if that test returns the correct data, and I'll reopen this issue.

**Comment by russback** [comment]
Hmm... oddly it's working for me locally using DDEV and https://vimeo.com/253905163 and https://vimeo.com/226053498 so I've not had to disable any plugins.

But it's not working on the remote hosting we have on Servd, and indeed on other setups of our own on Digital Ocean (via Laravel Forge).

`composer.lock` has `embed/embed` at `v4.4.11` which meets embedded assets' requirement of `v4.4.10`

Any other thoughts on what might be causing this in a particular environment given the packages and installed plugins will be the same?

**Comment by sjcallender** [comment]
Chiming in that we're experiencing the same issue on a Craft 4 site hosted on DigitalOcean. Videos load/play in DDEV, but not on the staging or production environments. Seems likely a Vimeo allow/deny list issue.

**Comment by ttempleton** [comment]
This is a similar (but outdated) issue on the Embed repo: https://github.com/oscarotero/Embed/issues/326

Unfortunately, any blocking of server IP addresses by Vimeo is something you would need to contact Vimeo about, and not something that Embedded Assets can work around.

**Comment by sjcallender** [comment]
Confirmed. Vimeo support unblocked our IP addresses and it's all working properly again.
