### ISSUE TITLE
Could not retrieve embed information

### ISSUE THREAD

**Issue by HAWilliams01** [benjamminf/craft-embedded-assets#268]
### Bug Description

Plugin not generating json video.

Craft version - 3.7.63.1
Embedded assets version 2.11.4

### Steps to reproduce

1. Paste any vimeo url into embed url field while viewing assets. {craft admin url}/assets/uploads

### Expected behaviour

The plugin should generate a json video for the vimeo url, but instead responds with the error "Could not retrieve embed information". I've tested this with several vimeo videos that are set to public privacy mode. It is working with Youtube videos just fine.

I checked the logs in storage/logs and found Invalid url '{url of vimeo video}' (Status code 429) in /craft/vendor/embed/embed/src/Embed.php:142 
I'm not sure why a 429 is being thrown or how the vimeo video url isn't being processed properly.

### Embedded Assets version

2.11.4

### Craft CMS version

3.7.63.1

**Comment by ttempleton** [comment]
This error is coming from the [Embed package, version 3](https://github.com/oscarotero/Embed/tree/v3.x), which is no longer actively maintained. Newer versions of Embedded Assets on newer versions of Craft use version 4 of Embed, and I've confirmed that embedding Vimeo videos works fine in those environments. So you will need to upgrade to at least Craft 4 and Embedded Assets 4.

(It's also worth noting that [Craft 3 is no longer supported](https://craftcms.com/knowledge-base/supported-versions), so you should upgrade to at least Craft 4 anyway.)

**Comment by erikberger** [comment]
While I completely agree that upgrading to Craft 4 is the ideal path for this issue, if you're in a bind with Craft 3 sites that rely heavily on using Vimeo embeds and a CMS upgrade isn't viable this little update appears to help. Simply adding 429 to the array of valid response codes in the Vimeo adapter.

![Screenshot 2024-07-26 at 12 09 23 PM](https://github.com/user-attachments/assets/4f794af0-a616-4ae2-be09-66fa8e7f7c18)

Obviously, not great to update dependencies directly like this but sometimes you just have to apply a patch for the time being.
