### ISSUE TITLE
Ability to manually refresh an asset

### ISSUE THREAD

**Issue by johndwells** [benjamminf/craft-embedded-assets#269]
### What would you like to see added to or changed in Embedded Assets, and why?

Our client recently embedded a Vimeo video into their Craft site, and afterwards updated the thumbnail image on Vimeo. This renders the JSON file stale with an out of date image link. In this scenario, how can the client "refresh" the JSON file to pick up the new information?

If I re-upload the video into the same volume folder, Craft does not ask me if I want to replace the existing file.

I am aware of the [console commands](https://github.com/spicywebau/craft-embedded-assets/blob/main/docs/console-commands.md) available to refresh a batch of embedded assets. However this is a rather heavy-handed tool when all we need is to refresh one asset in particular. And it's not something the client can do, they have to reach out to us for support.

It would therefore be great if there were some actions available somewhere in the CP to trigger for an individual embedded asset to be refreshed.

One obvious place would be on the asset index view in the CMS, when selecting the checkbox for the asset; another could be when editing the asset, perhaps under the Save dropdown menu.

Thanks for considering this request!

**Comment by ttempleton** [comment]
Just released 4.2.0 and 5.4.0 - the Assets page element indexes now show a refresh button when (only) embedded assets are selected.

<img width="1111" alt="Screenshot 2024-11-12 at 21 31 20" src="https://github.com/user-attachments/assets/20a5faf0-bba2-433a-9649-3cdc210ac2f4">
