### ISSUE TITLE
Plugin resources assets not loaded in Craft Cloud environment 

### ISSUE THREAD

**Issue by svale** [benjamminf/craft-embedded-assets#270]
### Bug Description

Hi,

I'm not sure if this is an issue that should be logged here or with Craft Cloud. 

It seems the plugin asset resources (CSS and JS) are not loaded when our CP is deployed to Craft Cloud environments

<img width="1233" alt="image" src="https://github.com/user-attachments/assets/b5166899-9149-4baf-bcf4-62481dfcc445">

<img width="578" alt="image" src="https://github.com/user-attachments/assets/7d5d22ed-dd2b-4732-8972-204fe729224e">

The plugin works as expected in the local DDEV env.

We have logged a similar report with Wrav oEmbed

___
System:
Craft Pro 5.3.0.3

Plugins
Amazon S3	2.2.1
Asset Usage	4.0.0
CKEditor	4.1.0
Embedded Assets	5.1.1
Expanded Singles	3.0.0
Feed Me	6.2.1
Field Manager	4.0.2
Formie	3.0.0
Hyper	2.0.3
Imager X	5.0.1
Imager X Craft Cloud Transformer	1.0.0-beta.1
Many to Many	4.0.0
oEmbed	3.0.9
Retcon	3.2.0
SEO	5.1.1
Sprig	3.2.1
Vite	5.0.0

### Steps to reproduce

1. Set up a Craft 5 site with the craft-embed-assets plugin 
2. Deploy to a Craft Cloud environment
3. Try to embed video

### Expected behaviour

Plugin resources (CSS/JS) should be loaded

### Embedded Assets version

5.1.1

### Craft CMS version

5.3.0.3

**Comment by timkelty** [comment]
@ttempleton Please reach out if you need any help. Here or @timkelty on Discord.

**Comment by svale** [comment]
FWIW, perhaps not the same under the hood, but a similar issue has been resolved here: https://github.com/wrav/oembed/issues/158#issuecomment-2283324980

If it can be of any help 🤞

**Comment by reganlawton** [comment]
Following @svale comment. If you need context on why my fixes work, you can hit me on Discord @reganlawton

**Comment by ttempleton** [comment]
Thanks everyone. I've ~~just enquired regarding~~ Craft Cloud access, and will update here with any updates/questions.

**Comment by timkelty** [comment]
@ttempleton The quickest change to get things working is to change any `getPublishedUrl` tags from this:

```
	{% set previewCss = view.getAssetManager().getPublishedUrl('@spicyweb/embeddedassets/assets/preview/dist/styles/preview.css', true) %}
```

to this:

```
	{% set previewCss = view.getAssetManager().getPublishedUrl('@spicyweb/embeddedassets/assets/preview/dist/', true, 'styles/preview.css') %}
```

Eg, https://github.com/verbb/formie/pull/1859/files

That said, in most cases, the proper way to do this is to simply call `registerAssetBundle` from the controller and not try and render the script/css tags yourself.

**Comment by ttempleton** [comment]
Thanks for that @timkelty!
@svale that is now working in Embedded Assets 4.1.2 and 5.1.2.

**Comment by svale** [comment]
Thanks @timkelty - much appreciated :)
