### ISSUE TITLE
Asset Preview fails with Apache 2.4 and asset URLs containing a "?"

### ISSUE THREAD

**Issue by hiasl** [benjamminf/craft-embedded-assets#274]
### Bug Description

When you're using Apache 2.4 with Craft and Embedded Assets, the preview fails because Apache rejects to rewrite URLs containing a` %3f` (encoded `?`). 

I can reproduce it with the latest a current version of DDEV (v1.23.4), Craft 5.4.6 and Embedded Assets 5.1.2.
Just make sure you change DDEV's config from nginx-fpm to apache-fpm.

The reason is that (at least newer) versions of Apache 2.4 return a 403 (Forbidden) on GET requests with ` %3f` in the query string, if the target of the rewrite contains a "?=". Since Embedded Assets uses a GET request to retrieve preview information, this applies e.g. to YouTube URLs like https://www.youtube.com/watch?v=Cq1ZSWAVpnU which is passed on to the preview action in an encoded way. `?` becomes ` %3f` and the following rewrite rule in .htaccess causes the 403: 

`RewriteRule (.+) index.php?p=$1 [QSA,L]`

Workaround: By changing the rewrite to 
`RewriteRule (.+) index.php [QSA,L]`
I could get it working. The difference is, that the rewrite target now does not contain a `?p=$1` and in that case Apache accepts the rewrite even with a `%3f`

For further information see the section UnsafeAllow3F (https://httpd.apache.org/docs/2.4/rewrite/flags.html#flag_unsafe_allow_3f) which is not active by default.

But maybe it would be better, if Embedded Assets would make a POST request instead of GET for the preview. I guess this should avoid the error even with the original rewrite rule as it is distributed by Craft.

### Steps to reproduce

1. Use DDEV and change the webserver_type from `nginx-fpm` to `apache-fpm` in .ddev/config.yaml
2. Install the latest Craft 5 and Embedded Assets
3. Create Filessytem / Volume
4. Got to Assets and use the "Embed" Button to preview a YouTube URL like https://www.youtube.com/watch?v=Cq1ZSWAVpnU (containing a ?)
5. The preview will fail
6. Change the rewrite rule in .htaccess to `RewriteRule (.+) index.php [QSA,L]`
7. The preview should work now

### Expected behaviour

I think the preview should work also with Craft's original rewrite rule any maybe this can easily be achieved by switching the request method of the XHR preview action call to POST.

I also issued a ticket with Craft because the problem is generally not Embedded Asset specific (but could be solved for the plugin itself): https://github.com/craftcms/cms/issues/15825

### Embedded Assets version

5.1.2

### Craft CMS version

5.4.6

**Comment by brandonkelly** [comment]
This is [resolved](https://github.com/craftcms/craft/commit/d9d7f51f5c00fa6e9e9a4f9ffc197a2f8737e7ae) for new projects going forward. Existing projects that run into this will need to manually modify their `web/.htaccess` file, changing this line:

```
RewriteRule (.+) index.php?p=$1 [QSA,L]
```

to

```
RewriteRule (.+) index.php [L]
```
