### ISSUE TITLE
Embedding Vimeo links

### ISSUE THREAD

**Issue by MathiasNftvf** [benjamminf/craft-embedded-assets#275]
### Bug Description

Using Craft 4.12.5 and trying to add a vimeo file . Embedding https://vimeo.com/1017938187 but the link preview says «verify to continue»

### Steps to reproduce

1. copy vimeo link
2. go to files
3. press embed

### Embedded Assets version

1

### Craft CMS version

4.12.5

**Comment by ttempleton** [comment]
This is working for me locally with the latest version (4.1.2) for Craft 4:

<img width="409" alt="Screenshot 2024-10-10 at 16 30 16" src="https://github.com/user-attachments/assets/cd6da0ed-a4f7-4f81-bd0c-9d67ab2ed118">

This does seem similar to https://github.com/spicywebau/craft-embedded-assets/issues/264 / https://github.com/oscarotero/Embed/issues/326 though, so I'll assume this is the same issue and recommend reading through those issues for some possible solutions.
