### ISSUE TITLE
GQL doesn't work when iframeSrc returns null value

### ISSUE THREAD

**Issue by laurabennett** [benjamminf/craft-embedded-assets#276]
### Bug Description

Internal server error The embedded asset code does not contain an iframe

### Steps to reproduce

Add a non Google url to embed assets such as live webcam
GQL query blows up because iframeCode and iframeSrc are null

### Expected behaviour

iframeSrc and iframeCode return null but don't cause an error or return empty string.
Guessing this plugin is only expected to work with certain domains but would be nice if it failed more gracefully

### Embedded Assets version

5.2.0

### Craft CMS version

5.4.9

**Comment by ttempleton** [comment]
If the page you're trying to embed from should include an iframe, and the domain isn't in the plugin's inbuilt whitelist, you can use the plugin's `extraWhitelist` setting to add it. This setting doesn't seem to be mentioned in the plugin's documentation, which is my mistake, but you would add something like the following to your Craft project's `config/embeddedassets.php` file:

```php
<?php

return [
    'extraWhitelist' => [
        'example.com',
    ],
];
```

For now, it's expected that `iframeCode` and `iframeSrc` will throw an exception when the embedded asset's code doesn't contain an iframe. It's worth considering whether they should return null instead, although I'm concerned about it being considered a breaking change at this point.

If I'm misunderstanding anything about the bug report, could you please post the URL and a minimal GQL query that reproduces this. If you'd prefer not to post any of this publicly, please feel free to send it in to plugins@spicyweb.com.au.

**Comment by laurabennett** [comment]
Is there a way to add the src that I want within the iframe? This is the url of our webcam https://g1.ipcamlive.com/player/player.php?alias=65a1b0c535eeb

**Comment by ttempleton** [comment]
Just released 5.3.0, where the code property of a newly-created embedded asset from an IPCamLive stream will contain an iframe. You will need to replace your existing embedded asset, and then the `iframeCode` and `iframeSrc` methods should work with it. Please let me know if any further issues occur, though.

**Comment by brogr** [comment]
@ttempleton, version 4 (4.2.3) is still affected though. When it can't construct iFrameCode or iFramceSrc, it results in `"message": "Something went wrong when processing the GraphQL query.",` error. Null values would be better/safer.

**Comment by ttempleton** [comment]
That's fair enough, although I'd be concerned about it being considered a breaking change at this point.
