### ISSUE TITLE
Embed URL from youtube is undefined

### ISSUE THREAD

**Issue by peirix** [benjamminf/craft-embedded-assets#281]
### Bug Description

When trying to embed a video from YouTube, the URL attribute in the json file just says `"url": "https://www.youtube.com/undefined"`, no matter which video I try to embed.

### Steps to reproduce

1. Copy a YouTube URL
2. Embed it
3. Download the JSON file and look at the URL attribute

### Embedded Assets version

2.11.4

### Craft CMS version

3.9.13

**Comment by ttempleton** [comment]
Embedded Assets just uses the data that the Embed package (in this case [version 3](https://github.com/oscarotero/Embed/tree/v3.x)) passes through, so either Embed or YouTube will be setting that. That said, [Embed 3 is no longer actively developed by its owner](https://github.com/oscarotero/Embed/issues/461#issuecomment-980560171), [Craft 3 is no longer supported](https://craftcms.com/knowledge-base/supported-versions#end-of-life-versions), and YouTube embeds do work as expected on Craft 4 and Embedded Assets 4, which uses [Embed 4](https://github.com/oscarotero/Embed/tree/master). So it's recommended that you upgrade to at least Craft 4 to resolve this.

**Comment by jrrdnx** [comment]
@peirix Found a quick fix for this that's working for us: https://github.com/reusserdesign/craft-embedded-assets/commit/960f0553bb1094ae2c9685b7b73d31236cb3766a

We understand Embed v3 and Craft v3 are no longer supported, but we've still got a lot of clients on those versions who aren't ready for a full upgrade to v4 yet so this works in the meantime.

**Comment by peirix** [comment]
@jrrdnx Thanks! That worked for us as well.
