### ISSUE TITLE
Bypass "Untrusted Source"

### ISSUE THREAD

**Issue by brimby** [benjamminf/craft-embedded-assets#282]
### What question would you like to ask?

I'm getting a warning about Panopto being an untrusted source, and so it's blocking the embed. Is there any way to override this or somehow whitelist Panopto to be used?
![Screenshot 2024-11-08 at 1 59 58 PM](https://github.com/user-attachments/assets/8762a929-d471-437f-9e84-20d28d709da5)

**Comment by ttempleton** [comment]
Yes - add the domain to the `extraWhitelist` setting in your Craft project's `config/embeddedassets.php` file:

```php
<?php

return [
    'extraWhitelist' => [
        'panopto.com',
    ],
];
```

(I recently realised this setting isn't actually documented anywhere - will try to correct that soon!)

**Comment by brogr** [comment]
@ttempleton friendly reminder to add this (and config/embeddedassets.php in general) to the documentation ;)
