### ISSUE TITLE
All youtube video error with "Could not find any embeddable media from this URL"

### ISSUE THREAD

**Issue by thinksitdo** [benjamminf/craft-embedded-assets#30]
Firstly, thanks for the plugin which has been working great ... until recently. Coming back to a project I was working on I am unable to add any youtube files. Any variation of the link gives the error "Could not find any embeddable media from this URL". This includes trying to re-add videos I have previously added or any random test. Previously embedded video currently in my asset folders work fine. Adding new vimeo embeds also works, just no youtube. Updated to 0.3.4 to see if it helped, but did'nt. Is this a known issue?

**Comment by thinksitdo** [comment]
Hi, any verification that this is an issue?

**Comment by thinksitdo** [comment]
Hi, any verification that this is an issue effecting more than just me?

**Comment by benjamminf** [comment]
Sorry I missed this issue! That's a strange issue – seems like YouTube is not allowing requests from your server?

Since you're on 0.3.4, have a look at the log file under `craft/storage/runtime/logs/embeddedassets.log`. Can you tell me what messages you get when requesting a YouTube URL?

**Comment by thinksitdo** [comment]
I looked for the logs but nothing was being generated. I uninstalled/deleted the plugin and reinstalled the latest version. It fixed whatever the issue was. Probably should have tried that first :) Thanks for the response.

**Comment by benjamminf** [comment]
Well then, that was unexpected haha. Can't say I have any idea on why a reinstall would have fixed this but I'm glad it's sorted 👍
