### ISSUE TITLE
Error uploading the file: This file type is not allowed

### ISSUE THREAD

**Issue by JamesMcFall** [benjamminf/craft-embedded-assets#32]
Hey Ben.
Thanks so much for building this plugin. It's made it so much easier to get users to post YouTube videos correctly :)

First off I'm using:

* Craft CMS 2.6.2940
* Embedded Assets 0.3.4

Every time I try to upload/embed an embedded asset I get this following error "**Error uploading the file: This file type is not allowed**".

The field type in use is a completely unrestricted asset field. So this doesn't appear to be me being dumb (I hope). I've used the plugin on plenty of other sites previously without issue.

I've tried a few different examples:

* https://vimeo.com/23776705
* https://www.youtube.com/watch?v=glii-kazad8
* https://www.youtube.com/embed/glii-kazad8

All result in the same error.
Any ideas?

Thanks in advance.

* * *

Uploading/embedding a YouTube link
![screen shot 2016-10-03 at 10 10 24 am](https://cloud.githubusercontent.com/assets/1585517/19023773/0aa5296c-8953-11e6-8162-14b0f51043ec.png)

The error
![screen shot 2016-10-03 at 10 10 29 am](https://cloud.githubusercontent.com/assets/1585517/19023775/0aa844ee-8953-11e6-9427-c3877f286356.png)

Test asset field showing no restrictions on upload type
![screen shot 2016-10-03 at 10 17 32 am](https://cloud.githubusercontent.com/assets/1585517/19023774/0aa551a8-8953-11e6-9009-719b20196bbd.png)

**Comment by benjamminf** [comment]
Hey James, no worries 👍  Craft doesn't allow JSON files by default – you need to add them as an allowed file type in your config. I'll refer to the [installation instructions](https://github.com/benjamminf/craft-embedded-assets#installation) on how to do this.

**Comment by JamesMcFall** [comment]
Oh no it was me being dumb! It's working now. Thanks for the reply.
