### ISSUE TITLE
YouTube Thumbnails

### ISSUE THREAD

**Issue by madebyspark** [benjamminf/craft-embedded-assets#34]
Hey there,

Thanks for such a great tool!

I am trying to display the YouTube thumbnails, but I'd like to use an image transform on them. Is that at all possible since the thumbnail url is a string?

Thx,
D.

**Comment by benjamminf** [comment]
Unfortunately as far as I'm aware Craft's image transforms can't be applied to external images. I personally use the [Imager](https://github.com/aelvan/Imager-Craft) plugin which does allow it.

I eventually plan on having thumbnails be supplied as proper asset models, so you can transform them. The plugin will be entirely reimagined and rewritten for Craft 3.

**Comment by sonoflee** [comment]
I know this is a really old issue, but wanted to see if there is any progress or plans to address it - I just ran into this when trying to use ImageOptimize or native transforms with an Embedded Asset.
