### ISSUE TITLE
Thumbnail and URL not showing up in Assets

### ISSUE THREAD

**Issue by toddprouty** [benjamminf/craft-embedded-assets#35]
On my local dev server, the embedded assets look great in Assets, with a thumbnail and the original YouTube URL included (once I added the 'Filename' column, of course):
![local server](https://monosnap.com/file/SxXaRJMQx3ug5ggIXoELELqgqjnmGX.png)

On the staging server, they look like this:
![staging server](https://monosnap.com/file/Px19MemhRURHcuSeUaB2iuCoj6KYRD.png)

Any idea what might cause this?

**Comment by madebyspark** [comment]
Hey Todd! Could be a stretch, but do you have "Assets in this source have public URLs" turned on in your asset sources settings for both environments?

**Comment by toddprouty** [comment]
Yes, it's on in both.

**Comment by benjamminf** [comment]
Seems to be similar behaviour to #29. Can you tell me what's showing up in your logs? This issue can been seen by a few people now, but I still don't really know why. I have encountered a similar problem myself when using CloudFlare's SSL feature, which due to how their service works makes reading files by cURL almost impossible (at least, I couldn't figure it out).

**Comment by toddprouty** [comment]
Yes, it does look similar. And as with the OP on #29, I'm using Serverpilot + DigitalOcean. I don't see anything of note in the EA log, but craft.log has this:

```
2016/10/07 16:28:26 [error] [application] Could not delete the file /srv/users/serverpilot/apps/realavid-staging/craft/storage/runtime/assets/thumbs/30/1097.jpg because the file does not exist.
2016/10/07 16:28:26 [error] [application] Could not delete the file /srv/users/serverpilot/apps/realavid-staging/craft/storage/runtime/assets/sources/1097.json because the file does not exist.
```

That probably showed up when I removed a video from an entry and then deleted it from Assets.

The video thumbnail, title, and description show up correctly during the process of adding it (blurred because it's for an unreleased product video):

![dialog](https://monosnap.com/file/zyM8DmZ80mSH24XyljSTDsFL35srg0.png)

I will send Serverpilot a link to this thread to see if they have any ideas.

**Comment by toddprouty** [comment]
From ServerPilot support:

> According to the issue that is linked in yours this appears to be an problem with the code grabbing variables and that it's having an issue when running behind a proxy (we configure Nginx as a reverse-proxy in front of Apache). If the author can't fix the issues so it can run behind a proxy it will most likely have problems with our config.

Also:

> ServerPilot uses the standard cURL installation, so there shouldn't be anything different about cURL on ServerPilot servers.

**Comment by toddprouty** [comment]
Now that I have the template code added and deployed to the staging server, I see that the nothing at all is being rendered to the page, unlike my local server where it works as expected.

**Comment by benjamminf** [comment]
I'll close this now that in 0.4.0 local embedded assets are read through their path and not their URL, which should solve this issue. If it's still not working, I'll reopen it.
