### ISSUE TITLE
Video Thumbnail show JSON filetype

### ISSUE THREAD

**Issue by kaspar-allenbach** [benjamminf/craft-embedded-assets#39]
Is there a way to show the youtube Thumbnails in the Controlpanel.

The thumnails are showing at upload:
![bildschirmfoto 2016-10-30 um 18 21 59](https://cloud.githubusercontent.com/assets/762213/19838355/cf20e33c-9ecd-11e6-8721-2edfb0d0f799.png)

But they disappear at save:
![bildschirmfoto 2016-10-30 um 18 22 06](https://cloud.githubusercontent.com/assets/762213/19838357/d587ce48-9ecd-11e6-85c0-d2598ba12c29.png)

Is this a Bug?

Craft CMS 2.6.2949 | PHP 7.0.12 | Embedded Assets 0.3.4

**Comment by superwick** [comment]
This is happening for me too. Furthermore, in list view, it shows the filename for the json file rather than the clickable URL of the video under "Filename", as I was expecting from seeing the demo screenshots. 

Craft 2.6.2952, PHP 5.6.26, plugin 0.3.4

**Comment by luizboaretto** [comment]
Same here! 

@benjamminf The problem for me is on "getMoreElements" (pagination)

**Comment by lboaretto** [comment]
I don't known it's the best solution... but it works:


On `EmbeddedIndex.js`
```
		initThumbnails: function()
		{
			var that = this;

			EmbeddedAssets.on('saveAsset', function(e)
			{
				that.assetIndex.updateElements();
			});

			this.assetIndex.on('updateElements', function(e)
			{
				var view = e.target.view;
				var $elements = view.getAllElements();

				view.on('appendElements', function(e)
				{
					var $elements2 = view.getAllElements();						
					EmbeddedAssets.applyThumbnails($elements2);
				});
			
				EmbeddedAssets.applyThumbnails($elements);
			});
		},
```

https://github.com/craftcms/cms/issues/2054

**Comment by benjamminf** [comment]
Craft 2 never had a built-in way to add custom thumbnails to assets. This meant resorting to some Javascript hackery. I'm not sure if I were ever going to get this perfect. With the release of Craft 3, I will not longer be fixing past issues on Craft 2. To be clear, this is no longer an issue on Craft 3 as it provides the necessary hooks to set custom thumbnails.
