### ISSUE TITLE
safeHtml strips allowfullscreen attribute

### ISSUE THREAD

**Issue by mfazio26** [benjamminf/craft-embedded-assets#40]
First, awesome plugin!

Second, I'm not sure if this is intentional or not, but `safeHtml` seems to be stripping some useful attributes that might be included in the original json response.

For example, if you add a YouTube video, the returned json has...
`html: "html": "\u003ciframe width=\"459\" height=\"344\" src=\"https:\/\/www.youtube.com\/embed\/iwGFalTRHDA?feature=oembed\" frameborder=\"0\" allowfullscreen\u003e\u003c\/iframe\u003e"`

But, when you use `safeHtml|raw` to output, the `allowfullscreen` is gone...
`<iframe width='1280' height='720' src='https://www.youtube.com/embed/AXaiBz7QOpY?feature=oembed' frameborder='0'></iframe>`

I'm assuming it gets stripped out because it doesn't have an `="..."`?

At the end of the day, for my use-case, its not a deal-breaker. But, figured it was worth mentioning.

**Comment by benjamminf** [comment]
The HTML purifier removes it. If you're okay with the slight security risk, you can use the `html` attribute which doesn't purify the embed data. I'll look into adding the fullscreen attribute as an exception.
