### ISSUE TITLE
Installation question

### ISSUE THREAD

**Issue by mostlyjan** [benjamminf/craft-embedded-assets#41]
I am sorry to be dense but when i add this line:
   'extraAllowedFileExtensions' => 'json'
to the file: 
  /craft/config/general.php
I get 500 errors.

Am i editing the correct file? Is there any additional info on the installation?
Appreciate any help you can provide. Thanks.

**Comment by mostlyjan** [comment]
sorry but i think all i had to do was add a comma at the end..

**Comment by benjamminf** [comment]
Seems like you've got some syntax error, can I see your whole general.php file?
