### ISSUE TITLE
Move actionParseUrl and actionSaveEmbeddedAsset logic to a service

### ISSUE THREAD

**Issue by timkelty** [benjamminf/craft-embedded-assets#42]
I was writing a task to convert some matrix fields to an assets field w/ embedded assets, so I needed to programmatically save some embedded assets, but since all the logic is in the controller, I had to duplicate. Would be ideal if it was a service!

**Comment by benjamminf** [comment]
Looking over it, I think the code in the controller is fine. All it does is create an EA model to pass to the `saveEmbeddedAsset` service method.

I suppose you'd want to cut down on setting all those attributes? I'm not sure why I didn't do it like this in the plugin, but you can set all of them at once using the `$model->setAttributes($oembedData);` method.

**Comment by timkelty** [comment]
Yeah I guess looking at it now there already services for those, so I was really duplicating setting attrs and the error catching.
