### ISSUE TITLE
Memory limit includeResources/_getThumbnails

### ISSUE THREAD

**Issue by timkelty** [benjamminf/craft-embedded-assets#43]
I bet you realize this already, but you can pretty easily run into memory limit issues if you have a lot of embedded assets.

I had this running on a production server, which had a little over 1000.

When I pulled the db down, I could no longer get into the CP at all, which I eventually tracked down to a memory limit by `JsonHelper::encode($this->_getThumbnails())` called from `EmbeddedAssetsPlugin::includeResources`.

**Comment by timkelty** [comment]
One way to at least circumvent this when moving between environments is change your `cacheMethod` to `db`.

**Comment by benjamminf** [comment]
Yeah I've known about this scalability issue for a while, just haven't had the time to work it out until now. I'm changing how thumbnails are retrieved where they aren't all generated in one go. I'll keep this updated.

**Comment by timkelty** [comment]
great, thanks!
