### ISSUE TITLE
Handle duplicates in folder

### ISSUE THREAD

**Issue by timkelty** [benjamminf/craft-embedded-assets#44]
Currently if enter the same url in the same folder, a duplicate is created.
Would be nice if it used the existing one if found.

**Comment by timkelty** [comment]
Actually I'm not sure what is supposed to happen on a duplicate...right now I get the "An unknown error occurred." flash, no asset is added, but an additional json file is still created.

**Comment by timkelty** [comment]
After some testing, it only happens on certain cases, eg: https://youtu.be/IkgyWsdRnx8

It seems to be because the filename doesn't match when it looks for a duplicate.
The filename that is uploaded first is `embed_What-To-Wear-Episode-2.json` but when it compares it with subsequent uploads, it is `embed_What-To-Wear-Episode-2-.json`

**Comment by timkelty** [comment]
Looks like you just need to do ```$fileName = AssetsHelper::cleanAssetName($filePrefix . $fileLabel . $fileExtension);```

PR coming :)

**Comment by benjamminf** [comment]
Interesting. I had that clean asset name call in there before but took it out because it was buggy with certain foreign characters, and then rolled my own. Thanks for pull request, merging now 👍
