### ISSUE TITLE
No Fullscreen at Vimeo and Youtube on default

### ISSUE THREAD

**Issue by smilefootage** [benjamminf/craft-embedded-assets#46]
Hey, 

i am adding the videos by help of the code:
{{ embed.safeHtml|raw }}

Soo far so fine, but for Vimeo and YouTube Videos no Fullscreen is available. 
Is there a possibility? For example something i can put into the parameters in the plugin settings in craft itself?

Best Regards,
Marcel

**Comment by smilefootage** [comment]
@benjamminf  so no idea dude how to solve this?

best,
marcel

**Comment by awcross** [comment]
Isn't this a dup of #40?

**Comment by smilefootage** [comment]
But still no solution i guess right?

**Comment by awcross** [comment]
No, but I would close this issue and comment on that one.

My guess it's an attribute in the `HTMLPurifier_Config` that needs to be allowed.

**Comment by smilefootage** [comment]
@awcross  thx. i will close it

**Comment by benjamminf** [comment]
@awcross is right, the HTML purifier removes it. If you're okay with the slight security risk, you can use the `html` attribute which doesn't purify the embed data.
