### ISSUE TITLE
Json file is not converted anymore in Craft

### ISSUE THREAD

**Issue by smilefootage** [benjamminf/craft-embedded-assets#47]
Hey,

on my local and stage server the plugin didnt make any problems.
But now on the live site, the json files are not generated anymore to the video link file.

See the attached screenshots :) what could be the problem?
Something with my provider/server or database? 

Best,
marcel

<img width="979" alt="bildschirmfoto 2017-01-23 um 17 55 53" src="https://cloud.githubusercontent.com/assets/8937525/22242998/d07be3d0-e225-11e6-99e9-2af60459aee9.png">

**Comment by AbbeyDesign** [comment]
I was just about to post a similar issue but mine is slightly different. I can embed Youtube videos, but this Russian one I tried today is a no go.

<img width="725" alt="assets_-_hurst_boiler_" src="https://cloud.githubusercontent.com/assets/11862097/22301866/7ea6fb8c-e2fa-11e6-8ecf-a42a10e31297.png">
