### ISSUE TITLE
Plugin not working if asset source path contains environment variable

### ISSUE THREAD

**Issue by pauliusef** [benjamminf/craft-embedded-assets#49]
If asset source settings uses an environment variable inside path setup, then the plugin won't read the file as the path isn't parsed. In `EmbeddedAssetsService` function `readAssetFile` local asset path isn't parsed before calling `realpath` function. The issue is fixed by passing the path through `craft()->config->parseEnvironmentString($path)` before `realpath`.

**Comment by benjamminf** [comment]
Thanks for the report, fixed now 👍
