### ISSUE TITLE
Possible to use embedded assets with the 'images' button in a rich text field?

### ISSUE THREAD

**Issue by JayBox325** [benjamminf/craft-embedded-assets#52]
Hi,

I have tried to add an embedded asset within a rich text field on a build and none of the embedded assets are appearing in the asset directory.

Is this field usable within a rich text field?

Thanks,
Jay

**Comment by benjamminf** [comment]
Unfortunately it's not possible to use these embed codes in rich text fields, and there are no plans to support it. Honestly though, there are better ways to include assets than through rich text fields. Complex content structures with embed codes and text are better suited to Matrix fields.
