### ISSUE TITLE
Unable to use CURL - can I work around?

### ISSUE THREAD

**Issue by JamesMcFall** [benjamminf/craft-embedded-assets#53]
Hey Ben.
Sorry I know this isn't quite the right venue for a question.

Due to a technical limitation with the way my hosting works (a bunch of docker images with an nginx proxy on front etc), I can't use CURL over https.

**When the plugin is just used for Youtube/Vimeo Is it safe to drop the CURL request from EmbeddedAssetsService->_readExternalFile() and rely just on the file_get_contents() call?**

It's just referencing a local json file so I'm thinking yes. You're obviously more familiar with what that might explode as a result though.

Thanks.

**Comment by benjamminf** [comment]
#38 should have fixed this for local files, and Craft 3 no longer relies on cURL to read embedded asset files.

However, cURL is required to read from external URL's to get the embed information.
