### ISSUE TITLE
Please add Facebook video?

### ISSUE THREAD

**Issue by ciaojames** [benjamminf/craft-embedded-assets#54]
Hi there! Would it be possible to get Facebook video to work?  They say they support oEmbed, but the plugin says it can't find any embeddable media with the URL. 
Fb oEmbed documentation: https://developers.facebook.com/docs/plugins/oembed-endpoints
Fb video API documentation: https://developers.facebook.com/docs/plugins/embedded-video-player#example

**Comment by benjamminf** [comment]
Now supported in the Craft 3 version.
