### ISSUE TITLE
Error Message breaks site

### ISSUE THREAD

**Issue by hansgohr** [benjamminf/craft-embedded-assets#59]
Hi I just moved my project to a web server and now I'm receiving error messages (with and without dev mode enabled) when I activate the plugin. 

> Argument 1 passed to Craft\EmbeddedAssetsVariable::fromAsset() must be an instance of Craft\AssetFileModel, null given

I've 'extraAllowedFileExtensions' => 'json' and 'devMode' => true in my general.php. The Server is running on php 5-56.

Do you have any idea how I could solve this?

> /craft/plugins/embeddedassets/variables/EmbeddedAssetsVariable.php(12)

```
<?php 
 namespace Craft;
 
 class EmbeddedAssetsVariable
 {
     public function isEmbedded(AssetFileModel $asset)
     {
         return craft()->embeddedAssets->getEmbeddedAsset($asset) !== null;
     } 
     public function fromAsset(AssetFileModel $asset)
     {
         return craft()->embeddedAssets->getEmbeddedAsset($asset);
     }
 
     public function fromAssets($assets, $indexBy = null)
     {
         return craft()->embeddedAssets->getEmbeddedAssets($assets, $indexBy);
     }
 }
```

**Comment by benjamminf** [comment]
It seems that you're passing in a null value to `craft.embeddedAssets.fromAsset()`. It might be because you forgot to upload all your assets to your server, which would explain why this is only happening on the staging server and not locally.
