### ISSUE TITLE
Uncaught TypeError: Craft.t is not a function

### ISSUE THREAD

**Issue by chasegiunta** [benjamminf/craft-embedded-assets#71]
Upon clicking "Embed" in the Assets CP section, nothing happens and this error is thrown.

This is on the newly latest 3.0.10.1, and I have a hunch it could potentially be due to some Garnish changes in this last release, but need some other testing.

**Comment by chasegiunta** [comment]
Might actually be bug with Craft's release today and will soon be addressed...
https://github.com/craftcms/cms/issues/2966

Will close once I can confirm

**Comment by brandonkelly** [comment]
99% sure it’s the same bug as #2966.

**Comment by brandonkelly** [comment]
3.0.10.2 is out with a fix.

**Comment by chasegiunta** [comment]
Yep, fixed. Thanks @brandonkelly
