### ISSUE TITLE
Error after upgrading to v0.2.0

### ISSUE THREAD

**Issue by dommmel** [benjamminf/craft-embedded-assets#8]
First: Big thanks for an awesome plugin. My client loves it!

Today I upgraded to Version 0.2.0 and it produces the following error 
    
    Fatal error: Class 'Opengraph\Opengraph' not found in /var/www/craft/app/framework/YiiBase.php on line 213

Thanks

**Comment by benjamminf** [comment]
Hey @dommmel, thanks!

I can't seem to reproduce this error. It seems like the Opengraph PHP library isn't being found for some reason. Can you check if the directory `craft/plugins/embeddedassets/vendor/euskadi31` exists? Don't know why it wouldn't be there, but might as well rule out the obvious.

**Comment by dommmel** [comment]
Thanks for the swift reply. 

Yes, the directory `craft/plugins/embeddedassets/vendor/euskadi31` exists.
Yes, I am using the previous version and it works just fine. Just wanted to let you know.

**Comment by andyharris** [comment]
I get the same error as of v0.2.0, so it isn't a one off.

**Comment by benjamminf** [comment]
@dommmel @andyharris sorry for the inconvenience! Currently at work but will look into it tonight. Little baffled as to what it could be though as I can't seem to reproduce it. Maybe I'll bypass composers autoload and require the libraries directly. Thanks for your patience fellas

**Comment by benjamminf** [comment]
Finally got around to fixing this!

**Comment by dommmel** [comment]
Thanks!

**Comment by andyharris** [comment]
Great, thanks. Really nice little addon this one, makes a big difference for our clients.
