### ISSUE TITLE
"Umlaut" in entry slug causes 'HTMLPurifier_Config' not found error

### ISSUE THREAD

**Issue by dommmel** [benjamminf/craft-embedded-assets#9]
Hi there. May have found a bug

When the plugin is installed and an entry's slug contains an Umlaut (such as ä,ö,ü) visiting the entry inside the CP results in the following error

    Fatal error: Class 'HTMLPurifier_Config' not found in /var/www/craft/plugins/embeddedassets/services/EmbeddedAssetsService.php on line 37

The error goes away by

- deactivating the plugin or 
- changing the URL in the browser adress bar from e.g. "admin/entries/sectionname/242-ääää" to "admin/entries/sectionname/242-somethingelse" or
- changing the entry slug to not contain an umlaut

**Comment by benjamminf** [comment]
Currently at work but will look into this tonight. Thanks for reporting!

**Comment by benjamminf** [comment]
By tonight I meant in two weeks. I'm able to reproduce this error. It's incredibly strange...

**Comment by benjamminf** [comment]
Got around this by explicitly requiring the purifier library. Still have no idea what the connection is between non-ASCII characters in slugs and the missing HTMLPurifier class, but maybe I don't want to know...
